<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CoursesList.aspx.cs" Inherits="HTCMS.Admin.CoursesList" MasterPageFile="~/Administrator.Master"%>


<asp:Content ID="Content1" runat="server" 
    contentplaceholderid="ContentPlaceHolder3">
    <div style="height:100%; width:100%; text-align:center; background-color:#F7F6F3">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
    CellPadding="4" DataKeyNames="Course_ID" DataSourceID="SqlDataSource1" 
    ForeColor="#333333" GridLines="None" style="margin:auto" Width="60%" 
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <Columns>
            <asp:BoundField DataField="Course_ID" HeaderText="Course_ID" ReadOnly="True" 
                SortExpression="Course_ID" />
            <asp:BoundField DataField="Course_Name" HeaderText="Course_Name" 
                SortExpression="Course_Name" />
            <asp:BoundField DataField="Credits" HeaderText="Credits" 
                SortExpression="Credits" />
        </Columns>
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <EditRowStyle BackColor="#999999" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
</asp:GridView>
        <br />
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
&nbsp;<asp:TextBox ID="TextBox2" runat="server"></asp:TextBox><asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>&nbsp;
        <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
            Text="Add Course" />
</div>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:HTCMSConnectionString %>" 
    
    
        SelectCommand="SELECT [Course ID] AS Course_ID, [Course Name] AS Course_Name, [Credits] FROM [Courses Available]" DeleteCommand="DELETE FROM [Courses Available]
WHERE [Course ID]=@Course_ID" UpdateCommand="UPDATE [Courses Available]
SET 
[Course Name]=@Course_Name,
[Credits]=@Credits
WHERE
[Course ID]=@Course_ID">
</asp:SqlDataSource>


</asp:Content>
