<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="StudentsList.aspx.cs" Inherits="HTCMS.Admin.StudentsList" EnableSessionState="True" MasterPageFile="~/Administrator.Master"%>

<asp:Content ID="Content1" runat="server" 
    contentplaceholderid="ContentPlaceHolder3">
    <div style="height:100%; width:100%; background-color:#F7F6F3">

    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        CellPadding="4" DataKeyNames="Roll_No" DataSourceID="SqlDataSource1" 
        ForeColor="#333333" GridLines="None" AutoGenerateEditButton="True" 
        AutoGenerateDeleteButton="True">
        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
        <Columns>
            <asp:BoundField DataField="Roll_No" HeaderText="Roll_No" ReadOnly="True" 
                SortExpression="Roll_No" />
            <asp:BoundField DataField="First_Name" HeaderText="First_Name" 
                SortExpression="First_Name" />
            <asp:BoundField DataField="Last_Name" HeaderText="Last_Name" 
                SortExpression="Last_Name" />
            <asp:BoundField DataField="Date_of_Birth" HeaderText="Date_of_Birth" 
                SortExpression="Date_of_Birth" />
            <asp:BoundField DataField="Gender" HeaderText="Gender" 
                SortExpression="Gender" />
            <asp:BoundField DataField="Admission_No" HeaderText="Admission_No" 
                SortExpression="Admission_No" />
            <asp:BoundField DataField="Nationality" HeaderText="Nationality" 
                SortExpression="Nationality" />
            <asp:BoundField DataField="Native_Country" HeaderText="Native_Country" 
                SortExpression="Native_Country" />
            <asp:BoundField DataField="Native_District" HeaderText="Native_District" 
                SortExpression="Native_District" />
            <asp:BoundField DataField="Religion" HeaderText="Religion" 
                SortExpression="Religion" />
            <asp:BoundField DataField="Mother_Tongue" HeaderText="Mother_Tongue" 
                SortExpression="Mother_Tongue" />
            <asp:BoundField DataField="Maritial_Status" HeaderText="Maritial_Status" 
                SortExpression="Maritial_Status" />
            <asp:BoundField DataField="Hostellite" HeaderText="Hostellite" 
                SortExpression="Hostellite" />
            <asp:BoundField DataField="Day_Scholar" HeaderText="Day_Scholar" 
                SortExpression="Day_Scholar" />
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            <asp:BoundField DataField="Mobile_No" HeaderText="Mobile_No" 
                SortExpression="Mobile_No" />
            <asp:BoundField DataField="Residential_Address" 
                HeaderText="Residential_Address" SortExpression="Residential_Address" />
            <asp:BoundField DataField="Residential_Phone_No" 
                HeaderText="Residential_Phone_No" SortExpression="Residential_Phone_No" />
            <asp:BoundField DataField="Father_Name" HeaderText="Father_Name" 
                SortExpression="Father_Name" />
            <asp:BoundField DataField="Father_Mobile_No" HeaderText="Father_Mobile_No" 
                SortExpression="Father_Mobile_No" />
            <asp:BoundField DataField="Father_Work_Address" 
                HeaderText="Father_Work_Address" SortExpression="Father_Work_Address" />
            <asp:BoundField DataField="Mother_Name" HeaderText="Mother_Name" 
                SortExpression="Mother_Name" />
            <asp:BoundField DataField="Mother_Mobile_No" HeaderText="Mother_Mobile_No" 
                SortExpression="Mother_Mobile_No" />
            <asp:BoundField DataField="Mother_Work_Address" 
                HeaderText="Mother_Work_Address" SortExpression="Mother_Work_Address" />
            <asp:BoundField DataField="Teacher" HeaderText="Teacher" 
                SortExpression="Teacher" />
        </Columns>
        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
        <EditRowStyle BackColor="#999999" />
        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
    </asp:GridView>
        <br />
        
        <asp:Button ID="Button1" runat="server" Text="Student Details" 
            onclick="Button1_Click" />
        <br />
        <asp:Panel ID="Panel1" runat="server"  Visible="false">
            <table style="width: 100%">
                <tr>
                    <td style="width:20%">
                        <asp:Label ID="Label2" runat="server" style="text-align: right" 
                            Text="First Name:"></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;<asp:TextBox ID="TextBox2" runat="server" AutoPostBack="True"></asp:TextBox></td>
                    <td>
                        <asp:Label ID="Label5" runat="server" Text="Gender:"></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:TextBox ID="TextBox5" runat="server" AutoPostBack="True"></asp:TextBox></td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="Label7" runat="server" Text="Last Name:"></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;<asp:TextBox ID="TextBox3" runat="server" AutoPostBack="True"></asp:TextBox></td>
                    <td>
                        <asp:Label ID="Label6" runat="server" Text="Admission No.:"></asp:Label>
                        &nbsp;<asp:TextBox ID="TextBox6" runat="server" AutoPostBack="True"></asp:TextBox><br />
                    </td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="Label4" runat="server" Text="Date of Birth:"></asp:Label>
                        &nbsp;<asp:TextBox ID="TextBox4" runat="server" AutoPostBack="True"></asp:TextBox></td>
                    <td>
                        <asp:Label ID="Label8" runat="server" Text="Roll No.:" ToolTip=" "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:TextBox ID="TextBox7" runat="server" AutoPostBack="True"></asp:TextBox></td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="Label29" runat="server" Text="Teacher Name:"></asp:Label>
                        &nbsp;<asp:TextBox ID="TextBox28" runat="server" AutoPostBack="True"></asp:TextBox></td>
                    <td>
                        <asp:Label ID="Label30" runat="server" Text="Username:"></asp:Label>
                        &nbsp;<asp:TextBox ID="TextBox29" runat="server" AutoPostBack="True"></asp:TextBox></td>
                    <td>
                        &nbsp;</td>
                </tr>
            </table>
        </asp:Panel>
        <br />
        <asp:Button ID="Button2" runat="server" Text="Personal Details" 
            onclick="Button2_Click" />
    
        <br />
        <asp:Panel ID="Panel2" runat="server" Visible="false">
        <table style="width: 100%">
            <tr>
                <td style="text-align: left; width:20%">
                    <asp:Label ID="Label9" runat="server" Text="Nationality:"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:TextBox ID="TextBox8" runat="server" AutoPostBack="True"></asp:TextBox>
                    <br />
                </td>
                <td style="text-align: left">
                    <asp:Label ID="Label14" runat="server" Text="Maritial Status:"></asp:Label>
&nbsp;
                    <asp:TextBox ID="TextBox13" runat="server" AutoPostBack="True"></asp:TextBox>
                    <br />
                </td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="Label10" runat="server" Text="Native Country:"></asp:Label>
&nbsp;
                    <asp:TextBox ID="TextBox9" runat="server" AutoPostBack="True"></asp:TextBox>
                    <br />
                </td>
                <td style="text-align: left">
                    <asp:Label ID="Label15" runat="server" Text="Hostellite:"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:TextBox ID="TextBox14" runat="server" AutoPostBack="True"></asp:TextBox>
                    <br />
                </td>
            </tr>
            <tr>
                <td style="text-align: left">
                    <asp:Label ID="Label11" runat="server" Text="Native District:"></asp:Label>
&nbsp;&nbsp;
                    <asp:TextBox ID="TextBox10" runat="server" AutoPostBack="True"></asp:TextBox>
                    <br />
                </td>
                <td style="text-align: left">
                    <asp:Label ID="Label16" runat="server" Text="Day Scholar:"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:TextBox ID="TextBox15" runat="server" AutoPostBack="True"></asp:TextBox>
                    <br />
                </td>
            </tr>
            <tr>
                <td style="text-align: left">
                    <asp:Label ID="Label12" runat="server" Text="Religion:"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:TextBox ID="TextBox11" runat="server" AutoPostBack="True"></asp:TextBox>
                    <br />
                </td>
                <td style="text-align: left">
                    <asp:Label ID="Label17" runat="server" Text="Email:"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:TextBox ID="TextBox16" runat="server" AutoPostBack="True"></asp:TextBox>
                    <br />
                </td>
            </tr>
            <tr>
                <td style="text-align: left">
                    <asp:Label ID="Label13" runat="server" Text="Mother Tongue:"></asp:Label>
&nbsp;
                    <asp:TextBox ID="TextBox12" runat="server" AutoPostBack="True"></asp:TextBox>
                    <br/>
                </td>
                <td style="text-align: left">
                    <asp:Label ID="Label18" runat="server" Text="Mobile No.:"></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:TextBox ID="TextBox17" runat="server" AutoPostBack="True"></asp:TextBox>
                    <br/>
                </td>
            </tr>
        </table>
        </asp:Panel>
        <br />
    
        <asp:Button ID="Button3" runat="server" Text="Communication Details" 
            onclick="Button3_Click" />
    
        <br />
        <asp:Panel ID="Panel3" runat="server" Visible="False">
        <div>
        
            <table style="width: 100%">
                <tr>
                    <td style="width: 20%">
                        <asp:Label ID="Label19" runat="server" Text="Residential Address:"></asp:Label>
                        &nbsp;&nbsp;<asp:TextBox ID="TextBox18" runat="server" 
                            TextMode="MultiLine" AutoPostBack="True"></asp:TextBox></td>
                    <td style="text-align: left">
                        <asp:Label ID="Label20" runat="server" Text="Residential Phone No.:"></asp:Label>
                        &nbsp; <asp:TextBox ID="TextBox19" runat="server" AutoPostBack="True"></asp:TextBox></td>
                </tr>
                <tr>
                    <td style="text-align: left; width: 567px;">
                        <asp:Label ID="Label21" runat="server" Text="Father's Name:"></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;<asp:TextBox 
                            ID="TextBox20" runat="server" AutoPostBack="True"></asp:TextBox><br />
                        </td>
                    <td style="text-align: left" rowspan="2">
                        <asp:Label ID="Label22" runat="server" Text="Father's Work Address:"></asp:Label>
                        &nbsp;&nbsp;<asp:TextBox ID="TextBox21" runat="server" TextMode="MultiLine" 
                            AutoPostBack="True"></asp:TextBox></td>
                </tr>
                <tr>
                    <td style="text-align: left; width: 567px;">
                        <asp:Label ID="Label27" runat="server" Text="Father's Mobile No.:"></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="TextBox26" runat="server" AutoPostBack="True"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td style="text-align: left; width: 567px;">
                        <asp:Label ID="Label24" runat="server" Text="Mother's Name:"></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
                        <asp:TextBox ID="TextBox23" runat="server" Height="22px" AutoPostBack="True"></asp:TextBox><br />
                        </td>
                    <td style="text-align: left" rowspan="2">
                        <asp:Label ID="Label26" runat="server" Text="Mother's Work Address:"></asp:Label>
                        &nbsp;&nbsp;<asp:TextBox ID="TextBox25" runat="server" TextMode="MultiLine" 
                            AutoPostBack="True"></asp:TextBox></td>
                </tr>
                <tr>
                    <td style="text-align: left; width: 567px;">
                        <asp:Label ID="Label28" runat="server" Text="Mother's Mobile No.:"></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="TextBox27" runat="server" AutoPostBack="True"></asp:TextBox>
                    </td>
                </tr>
            </table>
            </div>
            </asp:Panel>
        
        
        <br />
        <asp:Button ID="Button4" runat="server" onclick="Button4_Click" 
            Text="Add Record" />
        
        
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:HTCMSConnectionString %>" 
        
        
        SelectCommand="SELECT [Roll No] AS Roll_No, [First Name] AS First_Name, [Last Name] AS Last_Name, [Date of Birth] AS Date_of_Birth, [Gender], [Admission No] AS Admission_No, [Nationality], [Native Country] AS Native_Country, [Native District] AS Native_District, [Religion], [Mother Tongue] AS Mother_Tongue, [Maritial Status] AS Maritial_Status, [Hostellite], [Day Scholar] AS Day_Scholar, [Email], [Mobile No] AS Mobile_No, [Residential Address] AS Residential_Address, [Residential Phone No] AS Residential_Phone_No, [Father Name] AS Father_Name, [Father Mobile No] AS Father_Mobile_No, [Father Work Address] AS Father_Work_Address, [Mother Name] AS Mother_Name, [Mother Mobile No] AS Mother_Mobile_No, [Mother Work Address] AS Mother_Work_Address, [Teacher] FROM [Student Details]" UpdateCommand="UPDATE [Student Details]
SET
[First Name]=@First_Name,
[Last Name]=@Last_Name,
[Date of Birth]=@Date_of_Birth,
[Gender]=@Gender,
[Admission No]=@Admission_No,
[Nationality]=@Nationality,
[Native Country]=@Native_Country,
[Native District]=@Native_District,
[Religion]=@Religion,
[Mother Tongue]=@Mother_Tongue,
[Maritial Status]=@Maritial_Status,
[Hostellite]=@Hostellite,
[Day Scholar]=@Day_Scholar,
[Email]=@Email,
[Residential Address]=@Residential_Address,
[Residential Phone No]=@Residential_Phone_No,
[Father Name]=@Father_Name,
[Father Mobile No]=@Father_Mobile_No,
[Father Work Address]=@Father_Work_Address,
[Mother Name]=@Mother_Name,
[Mother Mobile No]=@Mother_Mobile_No,
[Mother Work Address]=@Mother_Work_Address,
[Teacher]=@Teacher
WHERE
[Roll No]=@Roll_No


" DeleteCommand="DELETE FROM [Student Details]
WHERE [Roll No]=@Roll_No">
    </asp:SqlDataSource>

</div>
    
</asp:Content>
